local lito = require("@lito")
local qt = require("@lito.qt")

local app = lito.target({ kind = "bin", name = "Qcm" })
local qt6 = lito.external_dependency(app, "qt6")
local proto = lito.external_source(app, "qcm-proto")

if lito.profile == "debug" then
  lito.target_add_generated_definition(app, "QCM_DEBUG_BUILD")
  lito.target_add_generated_definition(app, "QT_QML_DEBUG")
end

qt.protobuf({
  target = app,
  qt = qt6,
  source = proto,
  proto_files = {
    "filter.proto",
    "message.proto",
    "model.proto",
  },
  proto_includes = { "." },
  output = "Qcm/message",
  qml_uri = "Qcm.Msg",
  qml_version = "1.0",
})

qt.qml_module({
  target = app,
  qt = qt6,
  uri = "Qcm.App",
  version = "1.3",
  resource_prefix = "/",
  qml_files = {
    "qml/Global.qml",
    "qml/PlayBar.qml",
    "qml/PlayBarFlickable.qml",
    "qml/Util.qml",
    "qml/Window.qml",
    "qml/action/AddToMixAction.qml",
    "qml/action/AppendListAction.qml",
    "qml/action/CollectAction.qml",
    "qml/action/ColorSchemeAction.qml",
    "qml/action/CommentAction.qml",
    "qml/action/CopyAction.qml",
    "qml/action/FavoriteAction.qml",
    "qml/action/FilterAction.qml",
    "qml/action/GoToAlbumAction.qml",
    "qml/action/GoToArtistAction.qml",
    "qml/action/MixCreateAction.qml",
    "qml/action/MixDeleteAction.qml",
    "qml/action/MixLinkAction.qml",
    "qml/action/PlayAction.qml",
    "qml/action/PlayAllAction.qml",
    "qml/action/PlayNextAction.qml",
    "qml/action/SelectDisplayModeAction.qml",
    "qml/action/SettingAction.qml",
    "qml/action/ShuffleAllAction.qml",
    "qml/action/SubAction.qml",
    "qml/action/SyncItemAction.qml",
    "qml/component/auth/AuthEmail.qml",
    "qml/component/auth/AuthQr.qml",
    "qml/component/auth/AuthUsername.qml",
    "qml/component/basic/ByteSlider.qml",
    "qml/component/basic/DebugRect.qml",
    "qml/component/basic/GridView.qml",
    "qml/component/basic/HorizontalItemBar.qml",
    "qml/component/basic/Image.qml",
    "qml/component/basic/ImageCard.qml",
    "qml/component/basic/ItemView.qml",
    "qml/component/basic/Leaflet.qml",
    "qml/component/basic/RoundImage.qml",
    "qml/component/basic/RouteMsg.qml",
    "qml/component/filter/AlbumFilter.qml",
    "qml/component/filter/AlbumTitleFilter.qml",
    "qml/component/filter/AlbumTypeFilter.qml",
    "qml/component/filter/ArtistFilter.qml",
    "qml/component/filter/ArtistNameFilter.qml",
    "qml/component/filter/BaseFilter.qml",
    "qml/component/filter/DiscCountFilter.qml",
    "qml/component/filter/DurationFilter.qml",
    "qml/component/filter/EmptyFilter.qml",
    "qml/component/filter/FilterDelegateChooser.qml",
    "qml/component/filter/IntFilter.qml",
    "qml/component/filter/MixFilter.qml",
    "qml/component/filter/NameFilter.qml",
    "qml/component/filter/StringFilter.qml",
    "qml/component/filter/TitleFilter.qml",
    "qml/component/filter/TrackFilter.qml",
    "qml/component/filter/TypeFilter.qml",
    "qml/component/filter/TypeStringFilter.qml",
    "qml/component/filter/YearFilter.qml",
    "qml/component/misc/CardOverlay.qml",
    "qml/component/misc/CardPlayOverlay.qml",
    "qml/component/misc/ImagePlayCard.qml",
    "qml/component/misc/ListDescription.qml",
    "qml/component/misc/ListenIcon.qml",
    "qml/component/misc/OrderChip.qml",
    "qml/component/misc/SortOrderChip.qml",
    "qml/component/misc/SyncingLabel.qml",
    "qml/component/page/PageContainer.qml",
    "qml/component/page/PagePopup.qml",
    "qml/component/page/PageStack.qml",
    "qml/component/page/SettingBasePage.qml",
    "qml/component/player/LyricView.qml",
    "qml/component/player/Mpris.qml",
    "qml/component/player/PlaySlider.qml",
    "qml/component/player/VolumeButton.qml",
    "qml/component/setting/SettingRow.qml",
    "qml/component/setting/SettingSection.qml",
    "qml/component/tag/SongTag.qml",
    "qml/delegate/AlbumCardDelegate.qml",
    "qml/delegate/ArtistCardDelegate.qml",
    "qml/delegate/CommentDelegate.qml",
    "qml/delegate/ListItemDelegate.qml",
    "qml/delegate/MixCardDelegate.qml",
    "qml/delegate/PicCardGridDelegate.qml",
    "qml/delegate/ProgramDelegate.qml",
    "qml/delegate/SongDelegate.qml",
    "qml/dialog/AddToMixDialog.qml",
    "qml/dialog/FilterDialog.qml",
    "qml/dialog/GoToArtistDialog.qml",
    "qml/dialog/MixCreateDialog.qml",
    "qml/dialog/MixLinkDialog.qml",
    "qml/menu/AlbumFilterMenu.qml",
    "qml/menu/AlbumMenu.qml",
    "qml/menu/ArtistFilterMenu.qml",
    "qml/menu/ArtistMenu.qml",
    "qml/menu/DisplayModeMenu.qml",
    "qml/menu/EnumMenu.qml",
    "qml/menu/MixFilterMenu.qml",
    "qml/menu/MixMenu.qml",
    "qml/menu/ProgramMenu.qml",
    "qml/menu/RadioMenu.qml",
    "qml/menu/SongMenu.qml",
    "qml/menu/SortMenu.qml",
    "qml/page/AboutPage.qml",
    "qml/page/CommentPage.qml",
    "qml/page/DescriptionPage.qml",
    "qml/page/FilterPage.qml",
    "qml/page/HomePage.qml",
    "qml/page/LibraryPage.qml",
    "qml/page/MainPage.qml",
    "qml/page/PlayQueuePage.qml",
    "qml/page/PlayingPage.qml",
    "qml/page/ProviderAddPage.qml",
    "qml/page/ProviderMetaPage.qml",
    "qml/page/SearchPage.qml",
    "qml/page/StatusPage.qml",
    "qml/page/SyncPage.qml",
    "qml/page/detail/AlbumDetailPage.qml",
    "qml/page/detail/ArtistDetailPage.qml",
    "qml/page/detail/MixDetailPage.qml",
    "qml/page/detail/RadioDetailPage.qml",
    "qml/page/edit/ProviderEditPage.qml",
    "qml/page/setting/AudioSetting.qml",
    "qml/page/setting/MiscSetting.qml",
    "qml/page/setting/NetworkSetting.qml",
    "qml/page/setting/ProviderManagePage.qml",
    "qml/page/setting/QueueSetting.qml",
    "qml/page/setting/SettingPage.qml",
    "qml/page/setting/StorageSetting.qml",
    "qml/page/setting/ThemeSetting.qml",
    "qml/page/toplevel/LoadingPage.qml",
    "qml/page/toplevel/RetryPage.qml",
    "qml/page/toplevel/WelcomePage.qml",
  },
  singletons = {
    "qml/Global.qml",
    "qml/Util.qml",
  },
  resources = {
    "assets/Qcm.svg",
  },
  imports = {
    "QtCore",
    "QtQuick",
    "Qcm.Material",
    "Qcm.Msg",
  },
  moc_files = {
    { source = "src/action.cppm", mode = "module-split", output = "Qcm/action" },
    { source = "src/app.cppm", mode = "module-split", output = "Qcm/app" },
    { source = "src/backend.cppm", mode = "module-split", output = "Qcm/backend" },
    { source = "src/global.cppm", mode = "module-split", output = "Qcm/global" },
    {
      source = "src/image_provider/http.cppm",
      mode = "module-split",
      output = "Qcm/image_provider/http",
    },
    { source = "src/model/app_info.cppm", mode = "module-split", output = "Qcm/model/app_info" },
    {
      source = "src/model/empty_model.cppm",
      mode = "module-split",
      output = "Qcm/model/empty_model",
    },
    {
      source = "src/model/filter_rule_model.cppm",
      mode = "module-split",
      output = "Qcm/model/filter_rule_model",
    },
    { source = "src/model/id_queue.cppm", mode = "module-split", output = "Qcm/model/id_queue" },
    {
      source = "src/model/list_models.cppm",
      mode = "module-split",
      output = "Qcm/model/list_models",
    },
    { source = "src/model/lyric.cppm", mode = "module-split", output = "Qcm/model/lyric" },
    { source = "src/model/page_model.cppm", mode = "module-split", output = "Qcm/model/page_model" },
    {
      source = "src/model/play_queue.cppm",
      mode = "module-split",
      output = "Qcm/model/play_queue",
    },
    {
      source = "src/model/router_msg.cppm",
      mode = "module-split",
      output = "Qcm/model/router_msg",
    },
    {
      source = "src/model/sort_filter.cppm",
      mode = "module-split",
      output = "Qcm/model/sort_filter",
    },
    {
      source = "src/model/store_item.cppm",
      mode = "module-split",
      output = "Qcm/model/store_item",
    },
    {
      source = "src/model/table_proxy.cppm",
      mode = "module-split",
      output = "Qcm/model/table_proxy",
    },
    { source = "src/msg/store.cppm", mode = "module-split", output = "Qcm/msg/store" },
    { source = "src/notifier.cppm", mode = "module-split", output = "Qcm/notifier" },
    { source = "src/player.cppm", mode = "module-split", output = "Qcm/player" },
    {
      source = "src/qml/clipboard.cppm",
      mode = "module-split",
      output = "Qcm/qml/clipboard",
    },
    { source = "src/qml/duration.cppm", mode = "module-split", output = "Qcm/qml/duration" },
    { source = "src/qml/util.cppm", mode = "module-split", output = "Qcm/qml/util" },
    {
      source = "src/query/album_query.cppm",
      mode = "module-split",
      output = "Qcm/query/album_query",
    },
    {
      source = "src/query/artist_query.cppm",
      mode = "module-split",
      output = "Qcm/query/artist_query",
    },
    {
      source = "src/query/favorite_query.cppm",
      mode = "module-split",
      output = "Qcm/query/favorite_query",
    },
    {
      source = "src/query/lyric_query.cppm",
      mode = "module-split",
      output = "Qcm/query/lyric_query",
    },
    { source = "src/query/mix_query.cppm", mode = "module-split", output = "Qcm/query/mix_query" },
    {
      source = "src/query/play_query.cppm",
      mode = "module-split",
      output = "Qcm/query/play_query",
    },
    {
      source = "src/query/provider_query.cppm",
      mode = "module-split",
      output = "Qcm/query/provider_query",
    },
    { source = "src/query/qr_query.cppm", mode = "module-split", output = "Qcm/query/qr_query" },
    {
      source = "src/query/search_query.cppm",
      mode = "module-split",
      output = "Qcm/query/search_query",
    },
    {
      source = "src/query/storage_info.cppm",
      mode = "module-split",
      output = "Qcm/query/storage_info",
    },
    {
      source = "src/query/sync_query.cppm",
      mode = "module-split",
      output = "Qcm/query/sync_query",
    },
    {
      source = "src/status/app_state.cppm",
      mode = "module-split",
      output = "Qcm/status/app_state",
    },
    {
      source = "src/status/provider.cppm",
      mode = "module-split",
      output = "Qcm/status/provider",
    },
    {
      source = "include/Qcm/qml/enum.hpp",
      mode = "separate",
      output = "Qcm/qml/moc_enum.cpp",
    },
    {
      source = "include/Qcm/qml/foreign.hpp",
      mode = "include",
      output = "Qcm/qml/moc_foreign.cpp",
    },
    {
      source = "include/Qcm/register/qml_register.hpp",
      mode = "include",
      output = "Qcm/register/moc_qml_register.cpp",
    },
    {
      source = "src/message/include/Qcm/message/item_id.hpp",
      mode = "include",
      output = "Qcm/message/moc_item_id.cpp",
    },
  },
})
