[package]
name = "qcm-player"
version.workspace = true
standard = "c++23"

[lib]
name = "qcm-player"
module = "qcm.player"
archive = "qcm_player"
sources = [
  "metadata.cpp",
  "metadata.cppm",
  "mod.cppm",
  "notify.cppm",
  "player.cpp",
  "player.cppm",
]

[usage]
private-include-directories = ["."]
threads = true


[dependencies.qcm-core]
workspace = true
pub = true

[dependencies.rstd-std]
workspace = true

[dependencies.wavsen]
workspace = true

[dependencies.rstd-cppstd]
workspace = true

[[test]]
name = "playback"
sources = ["tests/playback.cpp"]
