[package]
name = "qcm-plugin-lua"
authors = ["hypengw <hypengwip@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
qcm-core = { workspace = true}
log = "0.4"
sea-orm = "1"
serde = "1.0"
serde_json = "1.0"
chrono = "0.4"
reqwest = "0.12"
async-trait = "0.1"
mlua-extra = { git = "https://github.com/hypengw/mlua-extra", rev = "df1d282170dd1718b8aeff405638c18cedd435ca" }

mlua = { version = "0.10", features = [
    "lua54",
    "async",
    "send",
    "error-send",
    "serialize",
] }
