# SplitSingleMocImpl.cmake
# ~~~
#
# This script splits a single .moc file into .moc.h (includes only) and .moc (implementation)
# This is an internal implementation file used by SplitMocFiles.cmake
#
# Required variables:
#   MOC_FILE - Path to the .moc file to process
#   MOC_BASE - Base name (e.g., "appModel" for "appModel.moc")
#   AUTOGEN_DIR - Directory where autogenerated files are located
# ~~~

if(NOT DEFINED MOC_FILE
   OR NOT DEFINED MOC_BASE
   OR NOT DEFINED AUTOGEN_DIR)
  message(
    FATAL_ERROR "Required variables not set: MOC_FILE, MOC_BASE, AUTOGEN_DIR")
endif()

# Check if the .moc file exists
if(NOT EXISTS "${MOC_FILE}")
  message(WARNING "MOC file does not exist: ${MOC_FILE}")
  return()
endif()

message(STATUS "Processing ${MOC_BASE}.moc...")

# Define output file paths
set(HEADER_FILE "${AUTOGEN_DIR}/${MOC_BASE}.moc.h")
set(SOURCE_FILE "${AUTOGEN_DIR}/${MOC_BASE}.moc.cpp")

# Read the entire .moc file
file(READ "${MOC_FILE}" MOC_CONTENT)

# Protect semicolons by replacing them with a placeholder
string(REPLACE ";" "<!SEMICOLON!>" MOC_CONTENT "${MOC_CONTENT}")

# Split into lines for processing
string(REPLACE "\n" ";" MOC_LINES "${MOC_CONTENT}")

# Initialize variables
set(HEADER_CONTENT "")
set(SOURCE_CONTENT "")
set(IN_HEADER_SECTION TRUE)

foreach(LINE ${MOC_LINES})
  # Restore semicolons in the line
  string(REPLACE "<!SEMICOLON!>" ";" LINE "${LINE}")

  # Check if this is an include line or comment/blank at the start
  string(REGEX MATCH "^#include" IS_INCLUDE "${LINE}")
  string(REGEX MATCH "^[ \t]*$" IS_BLANK "${LINE}")
  string(REGEX MATCH "^/\\*" IS_BLOCK_COMMENT_START "${LINE}")
  string(REGEX MATCH "^\\*" IS_BLOCK_COMMENT_CONTINUE "${LINE}")
  string(REGEX MATCH "^//" IS_LINE_COMMENT "${LINE}")

  # Determine if we're still in the header section (includes and initial
  # comments)
  if(IN_HEADER_SECTION)
    if(IS_INCLUDE
       OR IS_BLANK
       OR IS_BLOCK_COMMENT_START
       OR IS_BLOCK_COMMENT_CONTINUE
       OR IS_LINE_COMMENT)
      # Add to header
      set(HEADER_CONTENT "${HEADER_CONTENT}${LINE}\n")
    else()
      # We've hit the first non-include, non-comment line Switch to source
      # section
      set(IN_HEADER_SECTION FALSE)
      set(SOURCE_CONTENT "${SOURCE_CONTENT}${LINE}\n")
    endif()
  else()
    # Everything else goes to source
    set(SOURCE_CONTENT "${SOURCE_CONTENT}${LINE}\n")
  endif()
endforeach()

# Write the source file (overwrite the original .moc)
file(WRITE "${SOURCE_FILE}" "${SOURCE_CONTENT}")

# Write the header file
file(WRITE "${HEADER_FILE}" "${HEADER_CONTENT}")

message(STATUS "Split ${MOC_BASE}.moc -> ${MOC_BASE}.moc.h + ${MOC_BASE}.moc.cpp")
